# Generated by Django 6.0.5 on 2026-06-03 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(max_length=100, unique=True)),
                ('custom_name', models.CharField(blank=True, help_text='Other names', max_length=200)),
                ('genome_size_mb', models.FloatField(blank=True, help_text='Genome size in megabases', null=True)),
                ('chromosome_count', models.IntegerField(blank=True, null=True)),
                ('ploidy', models.CharField(blank=True, help_text='e.g., Diploid, Tetraploid', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('native_region', models.CharField(blank=True, max_length=200)),
                ('economic_importance', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='organisms/')),
                ('common_traits', models.JSONField(blank=True, default=list, help_text='List of common edited traits')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['common_name'],
            },
        ),
        migrations.CreateModel(
            name='OrganismCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category_type', models.CharField(choices=[('plant', 'Plant'), ('animal', 'Animal'), ('microorganism', 'Micro-organism'), ('fungus', 'Fungus'), ('algae', 'Algae'), ('insect', 'Insect'), ('fish', 'Fish'), ('bird', 'Bird'), ('mammal', 'Mammal'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="FontAwesome icon class (e.g., 'fa-seedling', 'fa-paw', 'fa-bacteria')", max_length=50)),
                ('color_code', models.CharField(blank=True, help_text="Hex color code for UI (e.g., '#5B7E96')", max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organism Category',
                'verbose_name_plural': 'Organism Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='crop_focus',
            field=models.CharField(blank=True, help_text='[DEPRECATED] Use organisms instead', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='organisms',
            field=models.ManyToManyField(blank=True, related_name='projects', to='core.organism'),
        ),
        migrations.AddField(
            model_name='project',
            name='primary_organism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_projects', to='core.organism'),
        ),
        migrations.AddField(
            model_name='organism',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisms', to='core.organismcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='organism',
            unique_together={('common_name', 'scientific_name')},
        ),
    ]
