# Generated by Django 6.0.5 on 2026-06-03 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organism_organismcategory_alter_project_crop_focus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='crop_focus',
        ),
    ]
