# Generated by Django 6.0.5 on 2026-06-23 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_project_crop_focus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='country',
        ),
        migrations.AddField(
            model_name='institution',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='institutions', to='core.country'),
        ),
        migrations.CreateModel(
            name='RegulatoryFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('functional', 'Functional Framework'), ('draft', 'Draft Guidelines (Genome Editing Specific)'), ('development', 'Policy Development'), ('none', 'No Specific Framework'), ('under_review', 'Under Review'), ('implemented', 'Fully Implemented')], default='development', max_length=20)),
                ('approach', models.CharField(choices=[('product_based', 'Product-based'), ('process_based', 'Process-based'), ('hybrid', 'Hybrid Approach'), ('not_specified', 'Not Specified')], default='not_specified', max_length=20)),
                ('summary', models.TextField(help_text='Summary of the regulatory framework for genome editing')),
                ('last_updated', models.DateField(auto_now=True)),
                ('biosafety_act_date', models.DateField(blank=True, null=True)),
                ('biosafety_regulations_date', models.DateField(blank=True, null=True)),
                ('ged_guidelines_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_framework', to='core.country')),
            ],
            options={
                'verbose_name': 'Regulatory Framework',
                'verbose_name_plural': 'Regulatory Frameworks',
                'ordering': ['country__name'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('instrument_type', models.CharField(choices=[('act', 'Act / Law'), ('regulation', 'Regulation'), ('guideline', 'Guideline'), ('policy', 'Policy'), ('protocol', 'Protocol'), ('standard', 'Standard'), ('other', 'Other')], max_length=20)),
                ('date_enacted', models.DateField(blank=True, null=True)),
                ('date_amended', models.DateField(blank=True, null=True)),
                ('coverage', models.CharField(choices=[('rd', 'Research & Development'), ('commercial', 'Commercialisation'), ('trade', 'Trade'), ('contained_use', 'Contained Use'), ('environmental_release', 'Environmental Release'), ('import_export', 'Import, Export & Transit'), ('labelling', 'Labelling'), ('ip', 'Intellectual Property'), ('all', 'All')], default='all', max_length=50)),
                ('summary', models.TextField(help_text='Brief summary of the instrument')),
                ('reference_url', models.URLField(blank=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='regulatory_instruments/')),
                ('is_current', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_instruments', to='core.regulatoryframework')),
            ],
            options={
                'verbose_name': 'Regulatory Instrument',
                'verbose_name_plural': 'Regulatory Instruments',
                'ordering': ['order', '-date_enacted'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('act_enacted', 'Act Enacted'), ('regulation_enacted', 'Regulation Enacted'), ('guideline_published', 'Guideline Published'), ('policy_adopted', 'Policy Adopted'), ('framework_established', 'Framework Established'), ('amendment', 'Amendment'), ('cft_approved', 'CFT Approved'), ('commercial_approved', 'Commercial Approval'), ('international_agreement', 'International Agreement Signed')], max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('reference', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_timeline', to='core.regulatoryframework')),
            ],
            options={
                'verbose_name': 'Regulatory Timeline',
                'verbose_name_plural': 'Regulatory Timeline',
                'ordering': ['event_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MultilateralAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_type', models.CharField(choices=[('cac', 'Codex Alimentarius Commission'), ('unfccc', 'UNFCCC Convention on Climate Change'), ('cbd', 'Convention on Biological Diversity'), ('cpb', 'Cartagena Protocol on Biosafety'), ('nagoya', 'Nagoya Protocol on Liability & Redress'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=300)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('ratified_date', models.DateField(blank=True, null=True)),
                ('accession_date', models.DateField(blank=True, null=True)),
                ('reference_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multilateral_agreements', to='core.regulatoryframework')),
            ],
            options={
                'verbose_name': 'Multilateral Agreement',
                'verbose_name_plural': 'Multilateral Agreements',
                'ordering': ['agreement_type'],
                'unique_together': {('framework', 'agreement_type')},
            },
        ),
        migrations.CreateModel(
            name='GedRegulatoryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('plants', 'Plants'), ('animals', 'Animals'), ('microorganisms', 'Micro-organisms'), ('health', 'Human Health'), ('environmental', 'Environmental')], default='plants', max_length=20)),
                ('status', models.CharField(choices=[('not_applicable', 'Not Applicable'), ('exempt', 'Exempt from GMO Regulation'), ('case_by_case', 'Case-by-Case Assessment'), ('requires_approval', 'Requires Approval'), ('commercial_approved', 'Commercial Approval Granted'), ('field_trials', 'Field Trials Approved'), ('research_allowed', 'Research Allowed'), ('prohibited', 'Prohibited'), ('pending', 'Pending Decision')], default='case_by_case', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the regulatory status')),
                ('notes', models.TextField(blank=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ged_regulatory_statuses', to='core.regulatoryframework')),
            ],
            options={
                'verbose_name': 'GEd Regulatory Status',
                'verbose_name_plural': 'GEd Regulatory Statuses',
                'ordering': ['category'],
                'unique_together': {('framework', 'category')},
            },
        ),
        migrations.CreateModel(
            name='RegulatoryInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('principal', 'Principal Competent Authority'), ('specialized', 'Specialized Regulatory Agency'), ('advisory', 'Advisory Body'), ('enforcement', 'Enforcement Agency'), ('policy', 'Policy Making Body'), ('ip', 'Intellectual Property Protection'), ('standards', 'Standards Body'), ('other', 'Other')], default='specialized', max_length=20)),
                ('mandate', models.TextField(help_text='Mandate/relevance to genome editing')),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_institutions', to='core.regulatoryframework')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_roles', to='core.institution')),
            ],
            options={
                'verbose_name': 'Regulatory Institution',
                'verbose_name_plural': 'Regulatory Institutions',
                'ordering': ['order', 'institution__name'],
                'unique_together': {('framework', 'institution')},
            },
        ),
    ]
