# Generated by Django 4.2.30 on 2026-06-23 12:47

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_infrastructurecategory_infrastructureassessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoryfacility',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='e.g., NARL', max_length=200),
        ),
        migrations.AlterField(
            model_name='laboratoryfacility',
            name='biosafety_level',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('bsl1', 'BSL 1'), ('bsl2', 'BSL 2'), ('bsl3', 'BSL 3'), ('bsl4', 'BSL 4'), ('none', 'Not Specified')], default=['none'], max_length=24),
        ),
        migrations.AlterField(
            model_name='laboratoryfacility',
            name='facility_type',
            field=models.CharField(blank=True, help_text='e.g., Molecular lab with PCR machines, glasshouses', max_length=200),
        ),
    ]
