# Generated by Django 4.2.30 on 2026-06-23 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_laboratoryfacility_abbreviation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoryfacility',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilitycountries', to='core.country'),
        ),
    ]
