# Generated by Django 4.2.30 on 2026-06-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_laboratoryfacility_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='ged_guidelines',
            field=models.TextField(blank=True, help_text='Genome Editing Guidelines status'),
        ),
    ]
