# Generated by Django 4.2.30 on 2026-06-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_country_ged_guidelines'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organism',
            options={'ordering': ['common_name'], 'verbose_name': 'Crops/Livestock/Organism'},
        ),
        migrations.AlterField(
            model_name='country',
            name='international_alignment',
            field=models.TextField(blank=True, help_text='Cartagena, AU Model Law, etc.'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='acronym',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
