# Generated by Django 4.2.30 on 2026-06-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_organism_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='acronym',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
