# Generated by Django 4.2.30 on 2026-06-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_institution_acronym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('rd', 'Research & Development'), ('cft', 'Confined Field Trial'), ('deployment', 'Deployment'), ('commercial', 'Commercialization'), ('completed', 'Completed')], default='rd', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(choices=[('crispr', 'CRISPR-Cas9'), ('talens', 'TALENs'), ('zfns', 'ZFNs'), ('sdn1', 'SDN-1'), ('sdn2', 'SDN-2'), ('sdn3', 'SDN-3'), ('base_editing', 'Base Editing'), ('prime_editing', 'Prime Editing'), ('bega', 'Base Editing & Gene Activation'), ('gene_drive', 'Gene Drive'), ('suicide_plasmid', 'Suicide plasmid')], max_length=20),
        ),
    ]
