# Generated by Django 4.2.30 on 2026-06-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_project_status_alter_project_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('research', 'Research Institution'), ('regulatory', 'Regulatory Body'), ('academic', 'Academic Institution'), ('private', 'Private Sector'), ('cso', 'Civil Society Organization'), ('regional', 'Regional/Continental Body'), ('international', 'International Partner'), ('government', 'Government Ministry'), ('dp', 'Development Partner/Funding Agency')], max_length=20),
        ),
        migrations.AlterField(
            model_name='organism',
            name='native_region',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organismcategory',
            name='category_type',
            field=models.CharField(choices=[('plant', 'Plant'), ('animal', 'Animal'), ('microorganism', 'Micro-organism'), ('fungus', 'Fungus'), ('algae', 'Algae'), ('insect', 'Insect'), ('fish', 'Fish'), ('bird', 'Bird'), ('forestry', 'Forestry'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_source',
            field=models.TextField(blank=True),
        ),
    ]
