# Generated by Django 4.2.30 on 2026-06-28 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_institution_type_alter_organism_native_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('research', 'Research Institution'), ('regulatory', 'Regulatory Body'), ('academic', 'Academic Institution'), ('private', 'Private Sector'), ('cso', 'Civil Society Organization'), ('regional', 'Regional/Continental Body'), ('international', 'International Partner/Body'), ('government', 'Government Ministry'), ('dp', 'Development Partner/Funding Agency')], max_length=20),
        ),
        migrations.CreateModel(
            name='NationalPriorityCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('cereals', 'Cereals and Grains'), ('legumes', 'Legumes and Pulses'), ('fruits', 'Fruits'), ('tuber', 'Root and Tubers'), ('oilcrops', 'Oil Crops'), ('industrial', 'Industrial Crops'), ('vegetables', 'Vegetables'), ('pasture', 'Pasture and Fodder'), ('fiber', 'Fiber Crops'), ('other', 'Other')], help_text='Crop category for grouping', max_length=50)),
                ('trait_improvement', models.TextField(help_text='Traits for improvement (e.g., Striga, drought stress, nutrition, yield)')),
                ('socio_economic_importance', models.TextField(help_text='Socio-economic importance of the crop')),
                ('ged_potential', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', help_text='GEd Potential (Low/Medium/High)', max_length=10)),
                ('existing_rd', models.CharField(blank=True, help_text='Existing R&D activities (e.g., Agronomy, Yes-Drought, Yes-Viruses)', max_length=200)),
                ('existing_rd_details', models.TextField(blank=True, help_text='Detailed description of existing R&D')),
                ('actual_annual_production', models.CharField(blank=True, help_text='Actual annual production capacity (tonnes) with citation', max_length=100)),
                ('actual_production_value', models.DecimalField(blank=True, decimal_places=2, help_text='Numeric value of actual production (tonnes)', max_digits=15, null=True)),
                ('actual_production_citation', models.CharField(blank=True, help_text='Citation for actual production (e.g., Orr et al. 2016)', max_length=200)),
                ('expected_annual_production', models.CharField(blank=True, help_text='Expected annual production capacity (tonnes)', max_length=100)),
                ('expected_production_value', models.DecimalField(blank=True, decimal_places=2, help_text='Numeric value of expected production (tonnes)', max_digits=15, null=True)),
                ('production_year', models.IntegerField(blank=True, help_text='Year of production data', null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order of display in the table')),
                ('data_source', models.TextField(default="South African National Agricultural and Development Strategy; Department of Agriculture's 2025–2030 Strategic Plan; Statistics South Africa", help_text='Source of the data')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_crops', to='core.country')),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_crops', to='core.organism')),
            ],
            options={
                'verbose_name': 'National Priority Crop for GEd',
                'verbose_name_plural': 'National Priority Crops for GEd',
                'ordering': ['display_order', 'category', 'organism__common_name'],
                'unique_together': {('country', 'organism')},
            },
        ),
    ]
