# Generated by Django 4.2.30 on 2026-06-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_institution_type_nationalprioritycrop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nationalprioritycrop',
            options={'ordering': ['display_order', 'organism__common_name'], 'verbose_name': 'National Priority Crop for GEd', 'verbose_name_plural': 'National Priority Crops for GEd'},
        ),
        migrations.RemoveField(
            model_name='nationalprioritycrop',
            name='category',
        ),
    ]
